### ISSUE TITLE
Latest version - 2.8.1 crashes in Protege 5.1.0

### ISSUE THREAD

**Issue by hsolbrig** [aehrc/snorocket#8]
Installed snorocket-protege-2.8.1-jar-with-dependencies.jar into the java/plugins directory.  Running the reasoner gives:

017-10-16 03:27:12.607 [Classification Thread] INFO  OWLReasonerManager    ------------------------------- Running Reasoner -------------------------------
2017-10-16 03:27:12.736 [Classification Thread] INFO  OWLReasonerManager    
2017-10-16 03:27:12.740 [Classification Thread] ERROR OWLReasonerManager    An error occurred during reasoning: org.semanticweb.owlapi.model.OWLOntology.importsClosure()Ljava/util/stream/Stream;.
java.lang.NoSuchMethodError: org.semanticweb.owlapi.model.OWLOntology.importsClosure()Ljava/util/stream/Stream;
	at au.csiro.snorocket.owlapi.SnorocketOWLReasoner.getAxioms(SnorocketOWLReasoner.java:274) ~[na:na]
	at au.csiro.snorocket.owlapi.SnorocketOWLReasoner.<init>(SnorocketOWLReasoner.java:141) ~[na:na]
	at au.csiro.snorocket.owlapi.SnorocketReasonerFactory.createReasoner(SnorocketReasonerFactory.java:42) ~[na:na]
	at org.protege.editor.owl.model.inference.ReasonerUtilities.createReasoner(ReasonerUtilities.java:20) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.ensureRunningReasonerInitialized(OWLReasonerManagerImpl.java:428) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:386) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_40]

**Comment by lawley** [comment]
Hi Harold ,

You have a version compatibility problem.

Snorocket 2.8.1 uses OWL API 5, but Protege  5.1.0 only uses a 4.x version of OWL API so they will not work together.

Did you install it manually or through the auto update mechanism?

Michael
